apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel-client-k8s-api
  namespace: tunnel-system
  labels:
    app.kubernetes.io/name: tunnel-client-k8s-api
    app.kubernetes.io/component: tunnel-client
    app.kubernetes.io/part-of: air-gapped-tunnel
    tunnel.type: k8s-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tunnel-client-k8s-api
      tunnel.type: k8s-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tunnel-client-k8s-api
        app.kubernetes.io/component: tunnel-client
        app.kubernetes.io/part-of: air-gapped-tunnel
        tunnel.type: k8s-api
      annotations:
        prometheus.io/scrape: "false"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: tunnel-client
        image: tunnel-client:latest
        imagePullPolicy: IfNotPresent
        args:
        - "-server=$(TUNNEL_SERVER_URL)"
        - "-token=$(TUNNEL_TOKEN)"
        - "-forward=6443:kubernetes.default.svc.cluster.local:443"
        - "-id=airgap-k8s-api"
        - "-improved=true"
        - "-metrics=true"
        - "-skip-verify=false"
        env:
        - name: TUNNEL_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: tunnel-config
              key: TUNNEL_SERVER_URL
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: tunnel-auth
              key: TUNNEL_TOKEN
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "pgrep -f tunnel-client"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "pgrep -f tunnel-client"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-run
          mountPath: /var/run
      volumes:
      - name: tmp
        emptyDir: {}
      - name: var-run
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30