apiVersion: v1
kind: Secret
metadata:
  name: tunnel-auth
  namespace: tunnel-system
  labels:
    app.kubernetes.io/name: tunnel-auth
    app.kubernetes.io/component: tunnel-client
type: Opaque
stringData:
  # Replace with your actual tunnel token
  TUNNEL_TOKEN: "your-production-token-here"